- description: "A single testimonial quote with a person's name, image, and company details"
  label: "Single Testimonial"
  name: "single_testimonial"
  sort: 2
  listed: true
  type: "block"
  parent: null
  content: "/content/single_testimonial.yaml"
  fields:
    - name: "job_title"
      label: "Job Title"
      description: "The job title of the person providing the quote."
      datatype: "text"
      sort: 4
      required: false
      relationship: null
      settings:
        defaultValue: "Financial Advisor"
        list: true
    - name: "quote"
      label: "Quote"
      description: "The testimonial or quote provided by a person."
      datatype: "textarea"
      sort: 1
      required: false
      relationship: null
      settings:
        defaultValue: "ABC Insurance has transformed my life with its reliable and affordable plans."
        list: true
    - name: "person_image"
      label: "Person Image"
      description: "The image of the person providing the quote."
      datatype: "images"
      sort: 2
      required: false
      relationship: null
      settings:
        defaultValue: "https://8-acd5dda19b-2fn6nn.manager.zesty.io/images/sb__person__image__1.png"
        list: true
    - name: "company_logo"
      label: "Company Logo"
      description: "The logo of the company the person represents."
      datatype: "images"
      sort: 7
      required: false
      relationship: null
      settings:
        defaultValue: "https://8-acd5dda19b-2fn6nn.manager.zesty.io/images/sb__company__logo__1.png"
        list: true
    - name: "position"
      label: "Position"
      description: "The person's position in their company."
      datatype: "text"
      sort: 5
      required: false
      relationship: null
      settings:
        defaultValue: "Senior Manager"
        list: true
    - name: "company_name"
      label: "Company Name"
      description: "The name of the company the person represents."
      datatype: "text"
      sort: 6
      required: false
      relationship: null
      settings:
        defaultValue: "ABC Insurance"
        list: true
    - name: "og_image"
      label: "Meta Image"
      description:
        "This field allows you to set an open graph image via the SEO tab. An Open Graph (OG) image is an image that
        appears on a social media post when a web page is shared."
      datatype: "images"
      sort: 8
      required: false
      relationship: null
      settings:
        defaultValue: null
        limit: 1
        list: false
    - name: "person_name"
      label: "Person Name"
      description: "The name of the person providing the quote."
      datatype: "text"
      sort: 3
      required: false
      relationship: null
      settings:
        defaultValue: "John Doe"
        list: true
